-- Foundation 7/7: data integrity, updated_at maintenance, working-day/salary
-- function fixes, index hygiene and statistics.
-- Data cleanup touches the showcase tenant (Nexus Orbits Pakistan) only.

-- ---------------------------------------------------------------------------
-- Showcase tenant cleanup (needed before the unique indexes below)
-- ---------------------------------------------------------------------------
-- Payslips regenerated by plain INSERT: keep the newest copy per (employee, month).
DELETE FROM public.payslips p
USING (
  SELECT id, row_number() OVER (PARTITION BY employee_id, month ORDER BY created_at DESC, id DESC) AS rn
  FROM public.payslips
  WHERE company_id = 'bc8defea-829f-4eeb-b210-6918e88e3019'
) d
WHERE p.id = d.id AND d.rn > 1;

-- Case-duplicate leave types: keep the most-used (then largest allowance, then oldest) and repoint references.
DROP TABLE IF EXISTS pg_temp._leave_type_merge;
CREATE TEMP TABLE _leave_type_merge AS
SELECT l.id,
       first_value(l.id) OVER (
         PARTITION BY l.company_id, lower(l.name)
         ORDER BY (SELECT count(*) FROM public.leave_requests r WHERE r.leave_type_id = l.id) DESC,
                  l.days_per_year DESC, l.created_at, l.id
       ) AS keep_id
FROM public.leave_types l
WHERE l.company_id = 'bc8defea-829f-4eeb-b210-6918e88e3019';

UPDATE public.leave_requests r SET leave_type_id = m.keep_id
FROM _leave_type_merge m WHERE r.leave_type_id = m.id AND m.id <> m.keep_id;
DELETE FROM public.leave_balances b
USING _leave_type_merge m
WHERE b.leave_type_id = m.id AND m.id <> m.keep_id
  AND EXISTS (SELECT 1 FROM public.leave_balances k WHERE k.employee_id = b.employee_id AND k.leave_type_id = m.keep_id AND k.year = b.year);
UPDATE public.leave_balances b SET leave_type_id = m.keep_id
FROM _leave_type_merge m WHERE b.leave_type_id = m.id AND m.id <> m.keep_id;
DELETE FROM public.leave_types l USING _leave_type_merge m WHERE l.id = m.id AND m.id <> m.keep_id;
DROP TABLE _leave_type_merge;

CREATE UNIQUE INDEX IF NOT EXISTS payslips_employee_month_uidx ON public.payslips (employee_id, month);
CREATE UNIQUE INDEX IF NOT EXISTS leave_types_company_lower_name_uidx ON public.leave_types (company_id, lower(name));

-- ---------------------------------------------------------------------------
-- Constraints (added NOT VALID, then validated: current data satisfies all)
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  c record;
BEGIN
  FOR c IN
    SELECT * FROM (VALUES
      ('tier_config', 'tier_config_company_id_fkey',
       'FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE'),
      ('attendance', 'attendance_status_chk',
       $c$CHECK (status IN ('present', 'absent', 'leave', 'short_leave', 'half_day', 'late', 'holiday'))$c$),
      ('employees', 'employees_status_chk',
       $c$CHECK (status IN ('active', 'inactive', 'on_leave', 'separated', 'terminated'))$c$),
      ('employees', 'employees_wage_chk', 'CHECK (wage_rate >= 0)'),
      ('leave_requests', 'leave_requests_dates_chk', 'CHECK (end_date >= start_date AND days_count > 0)'),
      ('leave_balances', 'leave_balances_days_chk', 'CHECK (total_days >= 0 AND used_days >= 0)'),
      ('overtime_records', 'overtime_records_hours_chk', 'CHECK (hours > 0 AND hours <= 24)'),
      ('payslips', 'payslips_amounts_chk', 'CHECK (gross_salary >= 0 AND net_salary >= 0 AND total_deductions >= 0)'),
      ('monthly_working_days', 'monthly_working_days_counts_chk',
       'CHECK (working_days_count BETWEEN 0 AND 31 AND daily_rate_divisor BETWEEN 1 AND 31)'),
      ('company_working_settings', 'company_working_settings_counts_chk',
       'CHECK (default_working_days_per_week BETWEEN 1 AND 7 AND default_working_days_per_month BETWEEN 0 AND 31 AND salary_divisor BETWEEN 1 AND 31)')
    ) AS v(tbl, con, def)
  LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = c.con AND conrelid = format('public.%I', c.tbl)::regclass) THEN
      EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I %s NOT VALID', c.tbl, c.con, c.def);
      EXECUTE format('ALTER TABLE public.%I VALIDATE CONSTRAINT %I', c.tbl, c.con);
    END IF;
  END LOOP;
END $$;

-- A vote's option must belong to the same poll.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'poll_options_id_poll_key' AND conrelid = 'public.poll_options'::regclass) THEN
    ALTER TABLE public.poll_options ADD CONSTRAINT poll_options_id_poll_key UNIQUE (id, poll_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'poll_votes_option_poll_fkey' AND conrelid = 'public.poll_votes'::regclass) THEN
    ALTER TABLE public.poll_votes ADD CONSTRAINT poll_votes_option_poll_fkey
      FOREIGN KEY (option_id, poll_id) REFERENCES public.poll_options (id, poll_id) ON DELETE CASCADE NOT VALID;
    ALTER TABLE public.poll_votes VALIDATE CONSTRAINT poll_votes_option_poll_fkey;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.tg_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.tg_set_updated_at() FROM PUBLIC, anon, authenticated;

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'working_days_config', 'monthly_working_days', 'company_working_settings', 'employee_documents',
    'leave_balances', 'leave_requests', 'overtime_config', 'overtime_records', 'tier_config'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS set_updated_at ON public.%I', t);
    EXECUTE format('CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at()', t);
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- Working days (set-based; fixes the inverted Saturday rule)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_working_days_for_month(target_company_id uuid, target_month date)
RETURNS TABLE(total_working_days integer, daily_rate_divisor integer, working_dates date[])
LANGUAGE sql STABLE
SET search_path = ''
AS $$
  WITH s AS (
    SELECT COALESCE(c.weekend_saturday, false) AS sat,
           COALESCE(c.weekend_sunday, true) AS sun,
           COALESCE(c.salary_divisor, 26) AS divisor
    FROM (SELECT 1) AS one
    LEFT JOIN public.company_working_settings c ON c.company_id = target_company_id
  ),
  m AS (
    SELECT mw.working_days_count, mw.daily_rate_divisor
    FROM public.monthly_working_days mw
    WHERE mw.company_id = target_company_id
      AND mw.month = date_trunc('month', target_month::timestamp)::date
  ),
  d AS (
    SELECT g::date AS dt
    FROM s,
         generate_series(date_trunc('month', target_month::timestamp),
                         date_trunc('month', target_month::timestamp) + interval '1 month - 1 day',
                         interval '1 day') AS g
    WHERE NOT (extract(dow FROM g) = 6 AND s.sat)
      AND NOT (extract(dow FROM g) = 0 AND s.sun)
      AND NOT EXISTS (
        SELECT 1 FROM public.events ev
        WHERE ev.company_id = target_company_id AND ev.date = g::date
          AND ev.affects_attendance AND ev.type IN ('holiday', 'off_day')
      )
  )
  SELECT COALESCE((SELECT m.working_days_count FROM m), (SELECT count(*)::integer FROM d)),
         COALESCE((SELECT m.daily_rate_divisor FROM m), (SELECT s.divisor FROM s)),
         COALESCE((SELECT array_agg(d.dt ORDER BY d.dt) FROM d), '{}'::date[])
$$;

-- Per employee: own weekend overrides, joining and separation dates, company holidays.
CREATE OR REPLACE FUNCTION public.get_employee_working_days_for_month(target_employee_id uuid, target_month date)
RETURNS TABLE(total_working_days integer, daily_rate_divisor integer, working_dates date[])
LANGUAGE sql STABLE
SET search_path = ''
AS $$
  WITH e AS (
    SELECT emp.company_id, emp.joining_date, emp.separation_date,
           COALESCE(emp.weekend_saturday, s.weekend_saturday, false) AS sat,
           COALESCE(emp.weekend_sunday, s.weekend_sunday, true) AS sun,
           COALESCE(emp.salary_divisor, s.salary_divisor, 26) AS divisor
    FROM public.employees emp
    LEFT JOIN public.company_working_settings s ON s.company_id = emp.company_id
    WHERE emp.id = target_employee_id
  ),
  b AS (
    SELECT date_trunc('month', target_month::timestamp)::date AS m_start,
           (date_trunc('month', target_month::timestamp) + interval '1 month - 1 day')::date AS m_end
  ),
  d AS (
    SELECT g::date AS dt
    FROM e, b,
         generate_series(GREATEST(b.m_start, COALESCE(e.joining_date, b.m_start))::timestamp,
                         LEAST(b.m_end, COALESCE(e.separation_date, b.m_end))::timestamp,
                         interval '1 day') AS g
    WHERE NOT (extract(dow FROM g) = 6 AND e.sat)
      AND NOT (extract(dow FROM g) = 0 AND e.sun)
      AND NOT EXISTS (
        SELECT 1 FROM public.events ev
        WHERE ev.company_id = e.company_id AND ev.date = g::date
          AND ev.affects_attendance AND ev.type IN ('holiday', 'off_day')
      )
  )
  SELECT (SELECT count(*)::integer FROM d),
         e.divisor,
         COALESCE((SELECT array_agg(d.dt ORDER BY d.dt) FROM d), '{}'::date[])
  FROM e
$$;

-- Single pass; pay comes from salary_history (as of month end), so callers
-- without Finance access (RLS) get zero money, never salaries.
CREATE OR REPLACE FUNCTION public.get_monthly_salary_stats(target_month date, in_company_id uuid)
RETURNS TABLE(total_calculated_salary numeric, total_budget_salary numeric, average_daily_rate numeric, employee_count integer)
LANGUAGE sql STABLE
SET search_path = ''
AS $$
  WITH b AS (
    SELECT date_trunc('month', target_month::timestamp)::date AS m_start,
           (date_trunc('month', target_month::timestamp) + interval '1 month - 1 day')::date AS m_end
  ),
  emp AS (
    SELECT e.id, e.joining_date, e.separation_date,
           COALESCE(e.salary_divisor, cws.salary_divisor, 26) AS divisor,
           COALESCE(sal.monthly_salary, 0) AS salary
    FROM public.employees e
    CROSS JOIN b
    LEFT JOIN public.company_working_settings cws ON cws.company_id = e.company_id
    LEFT JOIN LATERAL (
      SELECT sh.monthly_salary FROM public.salary_history sh
      WHERE sh.employee_id = e.id AND sh.effective_from <= b.m_end
      ORDER BY sh.effective_from DESC
      LIMIT 1
    ) sal ON true
    WHERE e.company_id = in_company_id
      AND (e.status = 'active' OR (e.separation_date IS NOT NULL AND e.separation_date >= b.m_start))
      AND (e.joining_date IS NULL OR e.joining_date <= b.m_end)
  ),
  att AS (
    SELECT a.employee_id,
           count(*) FILTER (WHERE a.status = 'present') AS present,
           count(*) FILTER (WHERE a.status = 'short_leave') AS short_leave
    FROM public.attendance a
    JOIN emp ON emp.id = a.employee_id
    CROSS JOIN b
    WHERE a.company_id = in_company_id
      AND a.date BETWEEN b.m_start AND b.m_end
      AND (emp.joining_date IS NULL OR a.date >= emp.joining_date)
      AND (emp.separation_date IS NULL OR a.date <= emp.separation_date)
    GROUP BY a.employee_id
  )
  SELECT COALESCE(sum(emp.salary / NULLIF(emp.divisor, 0) * (COALESCE(att.present, 0) + COALESCE(att.short_leave, 0) * 0.5)), 0)::numeric,
         COALESCE(sum(emp.salary), 0)::numeric,
         COALESCE(avg(emp.salary / NULLIF(emp.divisor, 0)), 0)::numeric,
         count(*)::integer
  FROM emp
  LEFT JOIN att ON att.employee_id = emp.id
$$;

REVOKE EXECUTE ON FUNCTION public.get_working_days_for_month(uuid, date),
  public.get_employee_working_days_for_month(uuid, date),
  public.get_monthly_salary_stats(date, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_working_days_for_month(uuid, date),
  public.get_employee_working_days_for_month(uuid, date),
  public.get_monthly_salary_stats(date, uuid) TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Index hygiene
-- ---------------------------------------------------------------------------
DROP INDEX IF EXISTS public.idx_attendance_employee_id;               -- covered by UNIQUE (employee_id, date)
DROP INDEX IF EXISTS public.idx_events_company_id;                    -- covered by (company_id, date)
DROP INDEX IF EXISTS public.idx_events_date;                          -- unused; reads are company-scoped
DROP INDEX IF EXISTS public.idx_monthly_working_days_company_id;      -- covered by UNIQUE (company_id, month)
DROP INDEX IF EXISTS public.idx_tier_config_company_id;               -- covered by UNIQUE (company_id, tier)
DROP INDEX IF EXISTS public.idx_leave_balances_employee_id;           -- covered by UNIQUE (employee_id, leave_type_id, year)
DROP INDEX IF EXISTS public.idx_overtime_records_company;             -- replaced by (company_id, date)
DROP INDEX IF EXISTS public.idx_overtime_records_date;                -- replaced by (company_id, date)
DROP INDEX IF EXISTS public.idx_overtime_records_status;              -- replaced by (company_id, status)
DROP INDEX IF EXISTS public.idx_employee_update_requests_company_id;  -- replaced by (company_id, status, created_at)
DROP INDEX IF EXISTS public.idx_employees_company_id;                 -- replaced by (company_id, status)
DROP INDEX IF EXISTS public.idx_profiles_company_id;                  -- replaced by (company_id, role)
DROP INDEX IF EXISTS public.idx_payslips_employee_id;                 -- covered by UNIQUE (employee_id, month)

CREATE INDEX IF NOT EXISTS idx_announcements_company_created ON public.announcements (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_announcements_created_by ON public.announcements (created_by);
CREATE INDEX IF NOT EXISTS idx_companies_created_by ON public.companies (created_by);
CREATE INDEX IF NOT EXISTS idx_complaints_company_created ON public.complaints (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_complaints_employee ON public.complaints (employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_documents_company_created ON public.employee_documents (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_employee_documents_uploaded_by ON public.employee_documents (uploaded_by);
CREATE INDEX IF NOT EXISTS idx_employee_update_requests_company_status ON public.employee_update_requests (company_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_employee_update_requests_reviewed_by ON public.employee_update_requests (reviewed_by);
CREATE INDEX IF NOT EXISTS idx_employees_company_status ON public.employees (company_id, status);
CREATE INDEX IF NOT EXISTS idx_employees_user_id ON public.employees (user_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_company_status ON public.leave_requests (company_id, status, start_date);
CREATE INDEX IF NOT EXISTS idx_leave_requests_reviewed_by ON public.leave_requests (reviewed_by);
CREATE INDEX IF NOT EXISTS idx_messages_company_created ON public.messages (company_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_pair_created ON public.messages (sender_id, receiver_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_receiver_unread ON public.messages (receiver_id) WHERE is_read = false;
CREATE INDEX IF NOT EXISTS idx_overtime_records_company_date ON public.overtime_records (company_id, date);
CREATE INDEX IF NOT EXISTS idx_overtime_records_company_status ON public.overtime_records (company_id, status);
CREATE INDEX IF NOT EXISTS idx_overtime_records_requested_by ON public.overtime_records (requested_by);
CREATE INDEX IF NOT EXISTS idx_overtime_records_reviewed_by ON public.overtime_records (reviewed_by);
CREATE INDEX IF NOT EXISTS idx_payslips_company_month ON public.payslips (company_id, month);
CREATE INDEX IF NOT EXISTS idx_payslips_generated_by ON public.payslips (generated_by);
CREATE INDEX IF NOT EXISTS idx_poll_options_poll ON public.poll_options (poll_id);
CREATE INDEX IF NOT EXISTS idx_poll_votes_employee ON public.poll_votes (employee_id);
CREATE INDEX IF NOT EXISTS idx_poll_votes_option_poll ON public.poll_votes (option_id, poll_id);
CREATE INDEX IF NOT EXISTS idx_polls_company_created ON public.polls (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_polls_created_by ON public.polls (created_by);

-- ---------------------------------------------------------------------------
-- Extensions and statistics
-- ---------------------------------------------------------------------------
DROP EXTENSION IF EXISTS pgjwt;   -- deprecated; nothing references it

ANALYZE;
