-- Engagement 2/4: private config, shared helpers and the staff (owner / HR) RPCs for
-- announcements, polls, complaints, messages and celebrations.
-- Every function is SECURITY DEFINER with an empty search_path, checks the caller's
-- role and company itself, and is granted only to the roles that need it.

-- ---------------------------------------------------------------------------
-- Private schema: server-side secrets (never exposed through the API)
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS engagement_private;
REVOKE ALL ON SCHEMA engagement_private FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS engagement_private.config (
  id boolean PRIMARY KEY DEFAULT true CONSTRAINT config_singleton_chk CHECK (id),
  function_url text,                -- push-send Edge Function
  webhook_secret text NOT NULL,     -- sent by the database to push-send
  chat_secret text NOT NULL,        -- derives the per-employee realtime topic
  vapid_public text,                -- generated by push-send on first use
  vapid_private jsonb,
  vapid_subject text NOT NULL DEFAULT 'https://umybjmuzbxfxdtbumgma.supabase.co',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE engagement_private.config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON engagement_private.config FROM PUBLIC, anon, authenticated;

INSERT INTO engagement_private.config (id, function_url, webhook_secret, chat_secret)
VALUES (
  true,
  'https://umybjmuzbxfxdtbumgma.supabase.co/functions/v1/push-send',
  encode(extensions.gen_random_bytes(32), 'hex'),
  encode(extensions.gen_random_bytes(32), 'hex')
)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Internal helpers (callable only from other definer functions)
-- ---------------------------------------------------------------------------

-- Company of an HR / owner caller, or an error.
CREATE OR REPLACE FUNCTION public._engagement_require_hr()
RETURNS uuid
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public.auth_company_id();
BEGIN
  IF auth.uid() IS NULL OR v_company IS NULL OR NOT public.auth_is_hr() THEN
    RAISE EXCEPTION 'Only HR can do this.' USING ERRCODE = '42501';
  END IF;
  RETURN v_company;
END;
$$;

-- "Today" for engagement dates (birthdays, wishes, greetings).
CREATE OR REPLACE FUNCTION public._engagement_today()
RETURNS date
LANGUAGE sql STABLE
SET search_path = ''
AS $$
  SELECT (now() AT TIME ZONE 'Asia/Karachi')::date
$$;

CREATE OR REPLACE FUNCTION public._engagement_staff_name(p_user uuid)
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(
    (SELECT NULLIF(btrim(concat_ws(' ', p.first_name, p.last_name)), '') FROM public.profiles p WHERE p.id = p_user),
    'HR'
  )
$$;

-- Announcement text without the formatting marks, for notification bodies.
CREATE OR REPLACE FUNCTION public._engagement_plain(p_text text)
RETURNS text
LANGUAGE sql IMMUTABLE
SET search_path = ''
AS $$
  SELECT btrim(regexp_replace(
    regexp_replace(
      regexp_replace(COALESCE(p_text, ''), '\[([^\]]*)\]\([^)]*\)', '\1', 'g'),  -- [label](url) -> label
      '(^|\s)(#{1,3}|-|\d+\.|>)\s', '\1', 'g'),                                 -- headings, bullets, quotes
    '[*_`~]+|\s+', ' ', 'g'))
$$;

-- Realtime broadcast topic of one employee's chat thread (unguessable, carries only message ids).
CREATE OR REPLACE FUNCTION public._engagement_chat_topic(p_employee uuid)
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT 'chat:' || encode(extensions.hmac(p_employee::text, c.chat_secret, 'sha256'), 'hex')
  FROM engagement_private.config c
  WHERE c.id
$$;

-- Tell the employee's open portal tabs that their thread changed. Never fails the caller.
CREATE OR REPLACE FUNCTION public._engagement_ping_thread(p_employee uuid, p_message uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM realtime.send(jsonb_build_object('id', p_message), 'message', public._engagement_chat_topic(p_employee), false);
EXCEPTION WHEN OTHERS THEN
  NULL;
END;
$$;

-- Fan-out to active employees (all, or one department). Returns how many were told.
CREATE OR REPLACE FUNCTION public._engagement_notify_employees(
  p_company uuid, p_department uuid, p_kind text, p_title text, p_body text, p_href text
)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_count integer;
BEGIN
  INSERT INTO public.notifications (company_id, employee_id, kind, title, body, href)
  SELECT p_company, e.id, p_kind, left(btrim(p_title), 200), NULLIF(left(p_body, 2000), ''), p_href
  FROM public.employees e
  WHERE e.company_id = p_company
    AND e.status = 'active'
    AND (p_department IS NULL OR e.department_id = p_department);
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

-- Occasions of active employees between two dates (inclusive).
-- Birthdays use day and month only; 29 February is celebrated on the 28th in other years.
CREATE OR REPLACE FUNCTION public._engagement_occasions(p_company uuid, p_from date, p_to date)
RETURNS TABLE (
  employee_id uuid, name text, rank text, avatar_url text, department text,
  kind text, years integer, on_date date, shared boolean
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  WITH days AS (
    SELECT d::date AS d
    FROM generate_series(p_from::timestamp, LEAST(p_to, p_from + 366)::timestamp, interval '1 day') AS g(d)
  ),
  people AS (
    SELECT e.id, e.name, e.rank, e.avatar_url, dep.name AS department, e.date_of_birth, e.joining_date, e.share_birthday
    FROM public.employees e
    LEFT JOIN public.departments dep ON dep.id = e.department_id
    WHERE e.company_id = p_company AND e.status = 'active'
  ),
  matches AS (
    SELECT p.*, d.d,
      CASE WHEN to_char(p.date_of_birth, 'MM-DD') = '02-29'
                AND NOT (extract(year FROM d.d)::int % 4 = 0 AND (extract(year FROM d.d)::int % 100 <> 0 OR extract(year FROM d.d)::int % 400 = 0))
           THEN '02-28' ELSE to_char(p.date_of_birth, 'MM-DD') END AS birth_md,
      CASE WHEN to_char(p.joining_date, 'MM-DD') = '02-29'
                AND NOT (extract(year FROM d.d)::int % 4 = 0 AND (extract(year FROM d.d)::int % 100 <> 0 OR extract(year FROM d.d)::int % 400 = 0))
           THEN '02-28' ELSE to_char(p.joining_date, 'MM-DD') END AS join_md
    FROM people p CROSS JOIN days d
  )
  SELECT m.id, m.name, m.rank, m.avatar_url, m.department, 'birthday', 0, m.d, m.share_birthday
  FROM matches m
  WHERE m.date_of_birth IS NOT NULL AND m.birth_md = to_char(m.d, 'MM-DD')
  UNION ALL
  SELECT m.id, m.name, m.rank, m.avatar_url, m.department, 'anniversary',
         (extract(year FROM m.d) - extract(year FROM m.joining_date))::int, m.d, true
  FROM matches m
  WHERE m.joining_date IS NOT NULL AND m.joining_date < m.d AND m.join_md = to_char(m.d, 'MM-DD')
    AND extract(year FROM m.d) > extract(year FROM m.joining_date)
  UNION ALL
  SELECT m.id, m.name, m.rank, m.avatar_url, m.department, 'welcome', 0, m.d, true
  FROM matches m
  WHERE m.joining_date = m.d
$$;

REVOKE ALL ON FUNCTION public._engagement_require_hr() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._engagement_today() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._engagement_staff_name(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._engagement_plain(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._engagement_chat_topic(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._engagement_ping_thread(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._engagement_notify_employees(uuid, uuid, text, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._engagement_occasions(uuid, date, date) FROM PUBLIC, anon, authenticated;

-- ===========================================================================
-- Announcements
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.engagement_announcements()
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
BEGIN
  RETURN (
    SELECT COALESCE(json_agg(json_build_object(
      'id', a.id, 'title', a.title, 'content', a.content, 'pinned', a.pinned, 'is_active', a.is_active,
      'audience', a.audience, 'department_id', a.department_id, 'department_name', d.name,
      'created_at', a.created_at, 'updated_at', a.updated_at,
      'author_name', public._engagement_staff_name(a.created_by),
      'edited_by_name', CASE WHEN a.updated_by IS NOT NULL THEN public._engagement_staff_name(a.updated_by) END
    ) ORDER BY a.pinned DESC, a.created_at DESC, a.id DESC), '[]'::json)
    FROM public.announcements a
    LEFT JOIN public.departments d ON d.id = a.department_id
    WHERE a.company_id = v_company
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_save_announcement(
  p_id uuid, p_title text, p_content text, p_pinned boolean DEFAULT false,
  p_audience text DEFAULT 'all', p_department uuid DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_title text := btrim(COALESCE(p_title, ''));
  v_content text := btrim(COALESCE(p_content, ''));
  v_pinned boolean := COALESCE(p_pinned, false);
  v_audience text := COALESCE(NULLIF(btrim(p_audience), ''), 'all');
  v_dept uuid;
  v_dept_name text;
  v_id uuid;
  v_told integer := 0;
BEGIN
  IF char_length(v_title) < 3 OR char_length(v_title) > 120 THEN
    RAISE EXCEPTION 'The title must be 3 to 120 characters.' USING ERRCODE = '22023';
  END IF;
  IF v_content = '' THEN
    RAISE EXCEPTION 'Write the announcement first.' USING ERRCODE = '22023';
  END IF;
  IF char_length(v_content) > 4000 THEN
    RAISE EXCEPTION 'The announcement can be at most 4000 characters.' USING ERRCODE = '22023';
  END IF;
  IF v_audience NOT IN ('all', 'department') THEN
    RAISE EXCEPTION 'Choose who should see it.' USING ERRCODE = '22023';
  END IF;
  IF v_audience = 'department' THEN
    SELECT d.id, d.name INTO v_dept, v_dept_name
    FROM public.departments d WHERE d.id = p_department AND d.company_id = v_company;
    IF v_dept IS NULL THEN
      RAISE EXCEPTION 'Choose the department that should see it.' USING ERRCODE = '22023';
    END IF;
  END IF;

  IF p_id IS NULL THEN
    INSERT INTO public.announcements (company_id, created_by, title, content, is_active, pinned, audience, department_id)
    VALUES (v_company, auth.uid(), v_title, v_content, true, v_pinned, v_audience, v_dept)
    RETURNING id INTO v_id;

    v_told := public._engagement_notify_employees(
      v_company, v_dept, 'announcement',
      CASE WHEN v_pinned THEN 'Pinned: ' ELSE '' END || v_title,
      left(public._engagement_plain(v_content), 140),
      '/portal/announcements'
    );
    PERFORM public.log_activity(
      'announcement.created',
      format('Posted the announcement "%s"%s', v_title, CASE WHEN v_dept_name IS NOT NULL THEN ' for ' || v_dept_name ELSE '' END),
      jsonb_build_object('announcement_id', v_id, 'pinned', v_pinned, 'audience', v_audience, 'department', v_dept_name, 'notified', v_told)
    );
  ELSE
    UPDATE public.announcements a
    SET title = v_title, content = v_content, pinned = v_pinned, audience = v_audience,
        department_id = v_dept, updated_by = auth.uid()
    WHERE a.id = p_id AND a.company_id = v_company
    RETURNING a.id INTO v_id;
    IF v_id IS NULL THEN
      RAISE EXCEPTION 'That announcement no longer exists.' USING ERRCODE = 'P0002';
    END IF;
    PERFORM public.log_activity(
      'announcement.updated', format('Edited the announcement "%s"', v_title),
      jsonb_build_object('announcement_id', v_id, 'pinned', v_pinned, 'audience', v_audience, 'department', v_dept_name)
    );
  END IF;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_set_announcement_active(p_id uuid, p_active boolean)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_title text;
BEGIN
  UPDATE public.announcements a SET is_active = COALESCE(p_active, false), updated_by = auth.uid()
  WHERE a.id = p_id AND a.company_id = v_company
  RETURNING a.title INTO v_title;
  IF v_title IS NULL THEN
    RAISE EXCEPTION 'That announcement no longer exists.' USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.log_activity(
    CASE WHEN p_active THEN 'announcement.shown' ELSE 'announcement.hidden' END,
    format('%s the announcement "%s"', CASE WHEN p_active THEN 'Showed' ELSE 'Hid' END, v_title),
    jsonb_build_object('announcement_id', p_id)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_delete_announcement(p_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_title text;
BEGIN
  DELETE FROM public.announcements a WHERE a.id = p_id AND a.company_id = v_company RETURNING a.title INTO v_title;
  IF v_title IS NULL THEN
    RAISE EXCEPTION 'That announcement no longer exists.' USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.log_activity('announcement.deleted', format('Deleted the announcement "%s"', v_title), jsonb_build_object('announcement_id', p_id));
END;
$$;

-- ===========================================================================
-- Polls
-- ===========================================================================

-- A poll is open while active and not past its closing time.
CREATE OR REPLACE FUNCTION public._engagement_poll_json(p_poll public.polls, p_with_counts boolean)
RETURNS json
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  WITH opts AS (
    SELECT o.id, o.option_text, o.position,
           (SELECT count(*) FROM public.poll_votes v WHERE v.option_id = o.id AND v.poll_id = o.poll_id)::int AS votes
    FROM public.poll_options o
    WHERE o.poll_id = p_poll.id
  ),
  total AS (SELECT COALESCE(sum(votes), 0)::int AS n FROM opts)
  SELECT json_build_object(
    'id', p_poll.id,
    'question', p_poll.question,
    'description', p_poll.description,
    'status', CASE WHEN p_poll.status = 'active' AND (p_poll.expires_at IS NULL OR p_poll.expires_at > now()) THEN 'open' ELSE 'closed' END,
    'expires_at', p_poll.expires_at,
    'closed_at', COALESCE(p_poll.closed_at, CASE WHEN p_poll.expires_at <= now() THEN p_poll.expires_at END),
    'created_at', p_poll.created_at,
    'author_name', public._engagement_staff_name(p_poll.created_by),
    'total_votes', CASE WHEN p_with_counts THEN (SELECT n FROM total) END,
    'eligible', CASE WHEN p_with_counts THEN (
      SELECT count(*)::int FROM public.employees e WHERE e.company_id = p_poll.company_id AND e.status = 'active'
    ) END,
    'options', (
      SELECT COALESCE(json_agg(json_build_object(
        'id', o.id, 'text', o.option_text, 'position', o.position,
        'votes', CASE WHEN p_with_counts THEN o.votes END,
        'percent', CASE WHEN (SELECT n FROM total) > 0 THEN round(o.votes * 100.0 / (SELECT n FROM total))::int ELSE 0 END
      ) ORDER BY o.position, o.id), '[]'::json)
      FROM opts o
    )
  )
$$;
REVOKE ALL ON FUNCTION public._engagement_poll_json(public.polls, boolean) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.engagement_polls()
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
BEGIN
  RETURN (
    SELECT COALESCE(json_agg(public._engagement_poll_json(p, true)
      ORDER BY (p.status = 'active' AND (p.expires_at IS NULL OR p.expires_at > now())) DESC, p.created_at DESC, p.id DESC), '[]'::json)
    FROM public.polls p
    WHERE p.company_id = v_company
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_poll_detail(p_id uuid)
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_poll public.polls;
BEGIN
  SELECT * INTO v_poll FROM public.polls p WHERE p.id = p_id AND p.company_id = v_company;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'That poll no longer exists.' USING ERRCODE = 'P0002';
  END IF;
  RETURN json_build_object(
    'poll', public._engagement_poll_json(v_poll, true),
    'voters', (
      SELECT COALESCE(json_agg(json_build_object(
        'employee_id', e.id, 'name', e.name, 'rank', e.rank, 'avatar_url', e.avatar_url,
        'option_id', o.id, 'option_text', o.option_text, 'voted_at', v.created_at
      ) ORDER BY o.position, o.id, v.created_at), '[]'::json)
      FROM public.poll_votes v
      JOIN public.employees e ON e.id = v.employee_id
      JOIN public.poll_options o ON o.id = v.option_id
      WHERE v.poll_id = v_poll.id
    ),
    'not_voted', (
      SELECT COALESCE(json_agg(json_build_object('employee_id', e.id, 'name', e.name, 'rank', e.rank, 'avatar_url', e.avatar_url) ORDER BY e.name), '[]'::json)
      FROM public.employees e
      WHERE e.company_id = v_company AND e.status = 'active'
        AND NOT EXISTS (SELECT 1 FROM public.poll_votes v WHERE v.poll_id = v_poll.id AND v.employee_id = e.id)
    )
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_create_poll(
  p_question text, p_description text, p_options text[], p_expires_at timestamptz DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_question text := btrim(COALESCE(p_question, ''));
  v_description text := NULLIF(btrim(COALESCE(p_description, '')), '');
  v_options text[];
  v_id uuid;
  v_told integer;
BEGIN
  IF char_length(v_question) < 5 OR char_length(v_question) > 200 THEN
    RAISE EXCEPTION 'The question must be 5 to 200 characters.' USING ERRCODE = '22023';
  END IF;
  IF char_length(COALESCE(v_description, '')) > 1000 THEN
    RAISE EXCEPTION 'The description can be at most 1000 characters.' USING ERRCODE = '22023';
  END IF;

  SELECT COALESCE(array_agg(o ORDER BY n), '{}') INTO v_options
  FROM (
    SELECT btrim(x) AS o, n FROM unnest(COALESCE(p_options, '{}'::text[])) WITH ORDINALITY AS u(x, n)
    WHERE NULLIF(btrim(x), '') IS NOT NULL
  ) s;

  IF cardinality(v_options) < 2 OR cardinality(v_options) > 6 THEN
    RAISE EXCEPTION 'Give the poll 2 to 6 options.' USING ERRCODE = '22023';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(v_options) o WHERE char_length(o) > 120) THEN
    RAISE EXCEPTION 'Each option can be at most 120 characters.' USING ERRCODE = '22023';
  END IF;
  IF (SELECT count(DISTINCT lower(o)) FROM unnest(v_options) o) <> cardinality(v_options) THEN
    RAISE EXCEPTION 'Each option must be different.' USING ERRCODE = '22023';
  END IF;
  IF p_expires_at IS NOT NULL AND p_expires_at <= now() + interval '5 minutes' THEN
    RAISE EXCEPTION 'The closing time must be in the future.' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.polls (company_id, created_by, question, description, status, expires_at)
  VALUES (v_company, auth.uid(), v_question, v_description, 'active', p_expires_at)
  RETURNING id INTO v_id;

  INSERT INTO public.poll_options (poll_id, company_id, option_text, position)
  SELECT v_id, v_company, o, (n - 1)::int FROM unnest(v_options) WITH ORDINALITY AS u(o, n);

  v_told := public._engagement_notify_employees(
    v_company, NULL, 'poll', 'New poll: ' || left(v_question, 160),
    COALESCE(left(v_description, 140), 'Cast your vote. It takes a second.'), '/portal/polls'
  );
  PERFORM public.log_activity(
    'poll.created', format('Started the poll "%s"', v_question),
    jsonb_build_object('poll_id', v_id, 'options', cardinality(v_options), 'expires_at', p_expires_at, 'notified', v_told)
  );
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_set_poll_status(p_id uuid, p_status text)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_question text;
BEGIN
  IF p_status NOT IN ('active', 'closed') THEN
    RAISE EXCEPTION 'Unknown poll status.' USING ERRCODE = '22023';
  END IF;
  UPDATE public.polls p
  SET status = p_status,
      closed_at = CASE WHEN p_status = 'closed' THEN now() END,
      -- Reopening a poll that ran out of time removes the deadline.
      expires_at = CASE WHEN p_status = 'active' AND p.expires_at <= now() THEN NULL ELSE p.expires_at END
  WHERE p.id = p_id AND p.company_id = v_company
  RETURNING p.question INTO v_question;
  IF v_question IS NULL THEN
    RAISE EXCEPTION 'That poll no longer exists.' USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.log_activity(
    CASE WHEN p_status = 'closed' THEN 'poll.closed' ELSE 'poll.reopened' END,
    format('%s the poll "%s"', CASE WHEN p_status = 'closed' THEN 'Closed' ELSE 'Reopened' END, v_question),
    jsonb_build_object('poll_id', p_id)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_delete_poll(p_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_question text;
BEGIN
  DELETE FROM public.polls p WHERE p.id = p_id AND p.company_id = v_company RETURNING p.question INTO v_question;
  IF v_question IS NULL THEN
    RAISE EXCEPTION 'That poll no longer exists.' USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.log_activity('poll.deleted', format('Deleted the poll "%s"', v_question), jsonb_build_object('poll_id', p_id));
END;
$$;

-- ===========================================================================
-- Complaints
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.engagement_complaints()
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
BEGIN
  RETURN (
    SELECT COALESCE(json_agg(json_build_object(
      'id', c.id, 'subject', c.subject, 'description', c.description, 'status', c.status,
      'is_anonymous', c.is_anonymous,
      'employee_id', CASE WHEN c.is_anonymous THEN NULL ELSE c.employee_id END,
      'employee_name', CASE WHEN c.is_anonymous THEN NULL ELSE e.name END,
      'employee_rank', CASE WHEN c.is_anonymous THEN NULL ELSE e.rank END,
      'employee_avatar', CASE WHEN c.is_anonymous THEN NULL ELSE e.avatar_url END,
      'response', c.response,
      'responder_name', CASE WHEN c.responded_by IS NOT NULL THEN public._engagement_staff_name(c.responded_by) END,
      'responded_at', c.responded_at, 'created_at', c.created_at, 'updated_at', c.updated_at
    ) ORDER BY CASE c.status WHEN 'pending' THEN 0 WHEN 'investigating' THEN 1 ELSE 2 END, c.created_at DESC, c.id DESC), '[]'::json)
    FROM public.complaints c
    LEFT JOIN public.employees e ON e.id = c.employee_id
    WHERE c.company_id = v_company
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_respond_complaint(p_id uuid, p_status text, p_response text)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_old public.complaints;
  v_response text := NULLIF(btrim(COALESCE(p_response, '')), '');
  v_status_changed boolean;
  v_response_changed boolean;
  v_title text;
BEGIN
  IF p_status NOT IN ('pending', 'investigating', 'resolved') THEN
    RAISE EXCEPTION 'Choose a status.' USING ERRCODE = '22023';
  END IF;
  IF char_length(COALESCE(v_response, '')) > 2000 THEN
    RAISE EXCEPTION 'The response can be at most 2000 characters.' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_old FROM public.complaints c WHERE c.id = p_id AND c.company_id = v_company FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'That complaint no longer exists.' USING ERRCODE = 'P0002';
  END IF;

  v_status_changed := v_old.status IS DISTINCT FROM p_status;
  v_response_changed := v_old.response IS DISTINCT FROM v_response;
  IF NOT v_status_changed AND NOT v_response_changed THEN
    RETURN;
  END IF;

  UPDATE public.complaints c
  SET status = p_status,
      response = v_response,
      responded_by = CASE WHEN v_response_changed THEN auth.uid() ELSE c.responded_by END,
      responded_at = CASE WHEN v_response_changed THEN now() ELSE c.responded_at END
  WHERE c.id = p_id;

  IF NOT v_old.is_anonymous AND v_old.employee_id IS NOT NULL THEN
    v_title := CASE
      WHEN v_status_changed AND p_status = 'resolved' THEN 'Your complaint was resolved'
      WHEN v_response_changed AND v_response IS NOT NULL THEN 'HR responded to your complaint'
      ELSE 'Your complaint is now ' || p_status
    END;
    PERFORM public.notify_employee(v_company, v_old.employee_id, 'complaint', v_title, v_old.subject, '/portal/complaints');
  END IF;

  IF v_status_changed THEN
    PERFORM public.log_activity(
      'complaint.status', format('Marked the complaint "%s" %s', v_old.subject, p_status),
      jsonb_build_object('complaint_id', p_id, 'from', v_old.status, 'to', p_status, 'anonymous', v_old.is_anonymous),
      CASE WHEN v_old.is_anonymous THEN NULL ELSE v_old.employee_id END
    );
  END IF;
  IF v_response_changed THEN
    PERFORM public.log_activity(
      'complaint.response', format('Responded to the complaint "%s"', v_old.subject),
      jsonb_build_object('complaint_id', p_id, 'anonymous', v_old.is_anonymous),
      CASE WHEN v_old.is_anonymous THEN NULL ELSE v_old.employee_id END
    );
  END IF;
END;
$$;

-- ===========================================================================
-- Messages (HR inbox)
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.engagement_threads()
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
BEGIN
  RETURN (
    WITH agg AS (
      SELECT m.employee_id,
             count(*) FILTER (WHERE m.sender_kind = 'employee' AND m.read_at IS NULL)::int AS unread
      FROM public.messages m
      WHERE m.company_id = v_company
      GROUP BY m.employee_id
    ),
    latest AS (
      SELECT DISTINCT ON (m.employee_id) m.employee_id, m.content, m.sender_kind, m.created_at
      FROM public.messages m
      WHERE m.company_id = v_company
      ORDER BY m.employee_id, m.created_at DESC, m.id DESC
    )
    SELECT COALESCE(json_agg(json_build_object(
      'employee_id', e.id, 'name', e.name, 'rank', e.rank, 'avatar_url', e.avatar_url, 'status', e.status,
      'department', d.name,
      'last_content', left(l.content, 160), 'last_from_staff', l.sender_kind = 'staff', 'last_at', l.created_at,
      'unread', a.unread
    ) ORDER BY l.created_at DESC), '[]'::json)
    FROM agg a
    JOIN latest l ON l.employee_id = a.employee_id
    JOIN public.employees e ON e.id = a.employee_id AND e.company_id = v_company
    LEFT JOIN public.departments d ON d.id = e.department_id
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_thread(p_employee uuid, p_limit integer DEFAULT 300)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_emp public.employees;
  v_limit integer := LEAST(GREATEST(COALESCE(p_limit, 300), 1), 1000);
BEGIN
  SELECT * INTO v_emp FROM public.employees e WHERE e.id = p_employee AND e.company_id = v_company;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'That employee is not in your company.' USING ERRCODE = 'P0002';
  END IF;

  -- Opening the thread reads what the employee sent.
  UPDATE public.messages m SET read_at = now()
  WHERE m.employee_id = v_emp.id AND m.company_id = v_company AND m.sender_kind = 'employee' AND m.read_at IS NULL;

  RETURN json_build_object(
    'employee', json_build_object(
      'id', v_emp.id, 'name', v_emp.name, 'rank', v_emp.rank, 'avatar_url', v_emp.avatar_url, 'status', v_emp.status,
      'department', (SELECT d.name FROM public.departments d WHERE d.id = v_emp.department_id)
    ),
    'messages', (
      SELECT COALESCE(json_agg(json_build_object(
        'id', x.id, 'content', x.content, 'sender_kind', x.sender_kind,
        'sender_name', CASE WHEN x.sender_kind = 'staff' THEN public._engagement_staff_name(x.sender_user_id) ELSE v_emp.name END,
        'mine', x.sender_user_id = auth.uid(),
        'created_at', x.created_at, 'read_at', x.read_at
      ) ORDER BY x.created_at, x.id), '[]'::json)
      FROM (
        SELECT m.* FROM public.messages m
        WHERE m.employee_id = v_emp.id AND m.company_id = v_company
        ORDER BY m.created_at DESC, m.id DESC
        LIMIT v_limit
      ) x
    )
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_send_message(p_employee uuid, p_content text)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_content text := btrim(COALESCE(p_content, ''));
  v_emp public.employees;
  v_row public.messages;
  v_name text := public._engagement_staff_name(auth.uid());
BEGIN
  IF v_content = '' THEN
    RAISE EXCEPTION 'Write a message first.' USING ERRCODE = '22023';
  END IF;
  IF char_length(v_content) > 2000 THEN
    RAISE EXCEPTION 'A message can be at most 2000 characters.' USING ERRCODE = '22023';
  END IF;
  SELECT * INTO v_emp FROM public.employees e WHERE e.id = p_employee AND e.company_id = v_company;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'That employee is not in your company.' USING ERRCODE = 'P0002';
  END IF;
  IF v_emp.status <> 'active' THEN
    RAISE EXCEPTION '% is no longer active, so they cannot read new messages.', v_emp.name USING ERRCODE = '22023';
  END IF;
  IF (SELECT count(*) FROM public.messages m
      WHERE m.sender_user_id = auth.uid() AND m.created_at > now() - interval '1 minute') >= 30 THEN
    RAISE EXCEPTION 'You are sending messages too quickly. Wait a moment.' USING ERRCODE = '54000';
  END IF;

  INSERT INTO public.messages (company_id, employee_id, sender_kind, sender_user_id, content)
  VALUES (v_company, v_emp.id, 'staff', auth.uid(), v_content)
  RETURNING * INTO v_row;

  -- HR has answered, so everything the employee sent is read.
  UPDATE public.messages m SET read_at = now()
  WHERE m.employee_id = v_emp.id AND m.sender_kind = 'employee' AND m.read_at IS NULL;

  PERFORM public.notify_employee(v_company, v_emp.id, 'message', format('New message from HR (%s)', v_name), left(v_content, 140), '/portal/messages');
  PERFORM public._engagement_ping_thread(v_emp.id, v_row.id);

  RETURN json_build_object(
    'id', v_row.id, 'content', v_row.content, 'sender_kind', v_row.sender_kind, 'sender_name', v_name,
    'mine', true, 'created_at', v_row.created_at, 'read_at', v_row.read_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_mark_thread_read(p_employee uuid)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_count integer;
BEGIN
  UPDATE public.messages m SET read_at = now()
  WHERE m.employee_id = p_employee AND m.company_id = v_company AND m.sender_kind = 'employee' AND m.read_at IS NULL;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

-- Employees HR can start a conversation with (active, no thread yet first).
CREATE OR REPLACE FUNCTION public.engagement_message_directory()
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
BEGIN
  RETURN (
    SELECT COALESCE(json_agg(json_build_object(
      'employee_id', e.id, 'name', e.name, 'rank', e.rank, 'avatar_url', e.avatar_url, 'department', d.name,
      'has_thread', EXISTS (SELECT 1 FROM public.messages m WHERE m.employee_id = e.id)
    ) ORDER BY e.name), '[]'::json)
    FROM public.employees e
    LEFT JOIN public.departments d ON d.id = e.department_id
    WHERE e.company_id = v_company AND e.status = 'active'
  );
END;
$$;

-- ===========================================================================
-- Celebrations
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.engagement_celebrations(p_days integer DEFAULT 30)
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_today date := public._engagement_today();
  v_days integer := LEAST(GREATEST(COALESCE(p_days, 30), 1), 90);
BEGIN
  RETURN json_build_object(
    'today', v_today,
    'occasions', (
      SELECT COALESCE(json_agg(json_build_object(
        'employee_id', o.employee_id, 'name', o.name, 'rank', o.rank, 'avatar_url', o.avatar_url, 'department', o.department,
        'kind', o.kind, 'years', o.years, 'date', o.on_date, 'days_until', o.on_date - v_today,
        'wishes', CASE WHEN o.on_date = v_today THEN (
          SELECT count(*)::int FROM public.celebration_wishes w
          WHERE w.employee_id = o.employee_id AND w.kind = o.kind AND w.occasion_date = o.on_date
        ) ELSE 0 END,
        'wished', CASE WHEN o.on_date = v_today THEN EXISTS (
          SELECT 1 FROM public.celebration_wishes w
          WHERE w.employee_id = o.employee_id AND w.kind = o.kind AND w.occasion_date = o.on_date AND w.from_user_id = auth.uid()
        ) ELSE false END
      ) ORDER BY o.on_date, CASE o.kind WHEN 'birthday' THEN 0 WHEN 'anniversary' THEN 1 ELSE 2 END, o.name), '[]'::json)
      FROM public._engagement_occasions(v_company, v_today, v_today + v_days - 1) o
      WHERE o.shared
    ),
    'recent_wishes', (
      SELECT COALESCE(json_agg(json_build_object(
        'id', w.id, 'kind', w.kind, 'date', w.occasion_date, 'message', w.message, 'created_at', w.created_at,
        'to_name', e.name,
        'from_name', CASE WHEN w.from_user_id IS NOT NULL THEN public._engagement_staff_name(w.from_user_id) ELSE fe.name END
      ) ORDER BY w.created_at DESC), '[]'::json)
      FROM (
        SELECT * FROM public.celebration_wishes w
        WHERE w.company_id = v_company AND w.occasion_date > v_today - 7
        ORDER BY w.created_at DESC LIMIT 30
      ) w
      JOIN public.employees e ON e.id = w.employee_id
      LEFT JOIN public.employees fe ON fe.id = w.from_employee_id
    )
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.engagement_send_wish(p_employee uuid, p_kind text, p_message text DEFAULT NULL)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_today date := public._engagement_today();
  v_message text := NULLIF(btrim(COALESCE(p_message, '')), '');
  v_id uuid;
  v_what text;
BEGIN
  IF char_length(COALESCE(v_message, '')) > 280 THEN
    RAISE EXCEPTION 'A wish can be at most 280 characters.' USING ERRCODE = '22023';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public._engagement_occasions(v_company, v_today, v_today) o
    WHERE o.employee_id = p_employee AND o.kind = p_kind AND o.shared
  ) THEN
    RAISE EXCEPTION 'There is nothing to celebrate for them today.' USING ERRCODE = '22023';
  END IF;
  IF (SELECT count(*) FROM public.celebration_wishes w WHERE w.from_user_id = auth.uid() AND w.created_at > now() - interval '1 hour') >= 60 THEN
    RAISE EXCEPTION 'That is a lot of wishes. Try again in a while.' USING ERRCODE = '54000';
  END IF;

  INSERT INTO public.celebration_wishes (company_id, employee_id, kind, occasion_date, from_user_id, message)
  VALUES (v_company, p_employee, p_kind, v_today, auth.uid(), v_message)
  ON CONFLICT (employee_id, kind, occasion_date, from_user_id) WHERE from_user_id IS NOT NULL DO NOTHING
  RETURNING id INTO v_id;

  IF v_id IS NULL THEN
    RETURN json_build_object('ok', true, 'already', true);
  END IF;

  v_what := CASE p_kind WHEN 'birthday' THEN 'a happy birthday' WHEN 'anniversary' THEN 'a happy work anniversary' ELSE 'a warm welcome' END;
  PERFORM public.notify_employee(
    v_company, p_employee, 'celebration',
    format('%s wished you %s 🎉', public._engagement_staff_name(auth.uid()), v_what),
    v_message, '/portal/celebrations'
  );
  RETURN json_build_object('ok', true, 'already', false);
END;
$$;

-- The week ahead for HR: holidays, events, occasions, and what is waiting for them.
CREATE OR REPLACE FUNCTION public.engagement_coming_up()
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public._engagement_require_hr();
  v_from date := public._engagement_today();
  v_to date := public._engagement_today() + 6;
BEGIN
  RETURN json_build_object(
    'from', v_from,
    'to', v_to,
    'items', (
      SELECT COALESCE(json_agg(x ORDER BY x.date, x.sort, x.title), '[]'::json)
      FROM (
        SELECT ev.date AS date, CASE WHEN ev.affects_attendance OR ev.type = 'holiday' THEN 'holiday' ELSE 'event' END AS kind,
               ev.title, initcap(replace(COALESCE(ev.type, 'event'), '_', ' ')) AS detail, '/events' AS href, 0 AS sort
        FROM public.events ev
        WHERE ev.company_id = v_company AND ev.date BETWEEN v_from AND v_to
        UNION ALL
        SELECT o.on_date, o.kind, o.name,
               CASE o.kind WHEN 'birthday' THEN 'Birthday'
                           WHEN 'anniversary' THEN o.years || CASE WHEN o.years = 1 THEN ' year' ELSE ' years' END || ' with the company'
                           ELSE 'First day' END,
               '/employees/' || o.employee_id, 1
        FROM public._engagement_occasions(v_company, v_from, v_to) o
        WHERE o.shared
      ) x
    ),
    'waiting', (
      SELECT COALESCE(json_agg(w ORDER BY w.sort), '[]'::json)
      FROM (
        SELECT 'leave requests' AS label, count(*)::int AS n, '/leave' AS href, 1 AS sort
        FROM public.leave_requests r WHERE r.company_id = v_company AND r.status = 'pending'
        UNION ALL
        SELECT 'overtime claims', count(*)::int, '/overtime-hours', 2
        FROM public.overtime_records r WHERE r.company_id = v_company AND r.status = 'pending'
        UNION ALL
        SELECT 'profile updates', count(*)::int, '/employee-updates', 3
        FROM public.employee_update_requests r WHERE r.company_id = v_company AND r.status = 'pending'
        UNION ALL
        SELECT 'complaints', count(*)::int, '/complaints', 4
        FROM public.complaints c WHERE c.company_id = v_company AND c.status = 'pending'
        UNION ALL
        SELECT 'unread messages', count(*)::int, '/messages', 5
        FROM public.messages m WHERE m.company_id = v_company AND m.sender_kind = 'employee' AND m.read_at IS NULL
      ) w
      WHERE w.n > 0
    )
  );
END;
$$;

-- From 09:00 company time, each person with an occasion today gets their greeting once
-- (bell + push). Run by pg_cron every 15 minutes; returns how many were greeted.
CREATE OR REPLACE FUNCTION public.engagement_send_morning_greetings()
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_local timestamp := now() AT TIME ZONE 'Asia/Karachi';
  v_today date := (now() AT TIME ZONE 'Asia/Karachi')::date;
  v_company record;
  v_occ record;
  v_first text;
  v_title text;
  v_body text;
  v_done integer := 0;
BEGIN
  IF extract(hour FROM v_local) < 9 THEN
    RETURN 0;
  END IF;
  FOR v_company IN SELECT c.id, c.name FROM public.companies c LOOP
    FOR v_occ IN SELECT * FROM public._engagement_occasions(v_company.id, v_today, v_today) LOOP
      INSERT INTO public.celebration_greetings (company_id, employee_id, kind, occasion_date)
      VALUES (v_company.id, v_occ.employee_id, v_occ.kind, v_today)
      ON CONFLICT (employee_id, kind, occasion_date) DO NOTHING;
      IF NOT FOUND THEN
        CONTINUE;
      END IF;
      v_first := split_part(btrim(v_occ.name), ' ', 1);
      IF v_occ.kind = 'birthday' THEN
        v_title := format('Happy birthday, %s! 🎂', v_first);
        v_body := format('Everyone at %s wishes you a wonderful year ahead.', v_company.name);
      ELSIF v_occ.kind = 'anniversary' THEN
        v_title := format('Happy work anniversary, %s! 🎉', v_first);
        v_body := format('%s %s at %s today. Thank you for all you do.', v_occ.years, CASE WHEN v_occ.years = 1 THEN 'year' ELSE 'years' END, v_company.name);
      ELSE
        v_title := format('Welcome to %s, %s! 👋', v_company.name, v_first);
        v_body := 'Today is your first day. We are glad you are here.';
      END IF;
      PERFORM public.notify_employee(v_company.id, v_occ.employee_id, 'celebration', v_title, v_body, '/portal/celebrations');
      v_done := v_done + 1;
    END LOOP;
  END LOOP;
  RETURN v_done;
END;
$$;

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public.engagement_announcements() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_save_announcement(uuid, text, text, boolean, text, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_set_announcement_active(uuid, boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_delete_announcement(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_polls() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_poll_detail(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_create_poll(text, text, text[], timestamptz) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_set_poll_status(uuid, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_delete_poll(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_complaints() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_respond_complaint(uuid, text, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_threads() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_thread(uuid, integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_send_message(uuid, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_mark_thread_read(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_message_directory() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_celebrations(integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_send_wish(uuid, text, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_coming_up() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.engagement_send_morning_greetings() FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.engagement_announcements() TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_save_announcement(uuid, text, text, boolean, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_set_announcement_active(uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_delete_announcement(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_polls() TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_poll_detail(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_create_poll(text, text, text[], timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_set_poll_status(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_delete_poll(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_complaints() TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_respond_complaint(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_threads() TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_thread(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_send_message(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_mark_thread_read(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_message_directory() TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_celebrations(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_send_wish(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.engagement_coming_up() TO authenticated;
