-- Engagement 4/4: web push. Every notifications row is pushed to the recipient's devices.
--   * Browsers subscribe through push_subscribe (staff) / portal_push_subscribe (portal).
--   * AFTER INSERT on notifications queues an async HTTP call (pg_net) to the 'push-send'
--     Edge Function with only the notification id and a shared secret (plus the anon JWT for
--     the verify_jwt gateway).
--   * push-send reads the row and the VAPID key pair with the service role, encrypts
--     (RFC 8291 aes128gcm) and posts to each device, pruning dead subscriptions.
--   * The VAPID private key lives only in engagement_private.config (service role via
--     _push_config); it is generated by push-send on first use.
--   * pg_cron sends the 09:00 celebration greetings.

DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pg_net is not available (%); push delivery stays off until it is enabled.', SQLERRM;
END $$;

-- ---------------------------------------------------------------------------
-- Keys and config for the Edge Function (service role only)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.push_public_key()
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT c.vapid_public FROM engagement_private.config c WHERE c.id
$$;
REVOKE ALL ON FUNCTION public.push_public_key() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.push_public_key() TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public._push_config()
RETURNS json
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT json_build_object(
    'webhook_secret', c.webhook_secret,
    'vapid_public', c.vapid_public,
    'vapid_private', c.vapid_private,
    'vapid_subject', c.vapid_subject
  )
  FROM engagement_private.config c WHERE c.id
$$;
REVOKE ALL ON FUNCTION public._push_config() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public._push_config() TO service_role;

-- Stores the key pair once; concurrent first calls converge on the stored pair.
CREATE OR REPLACE FUNCTION public._push_store_vapid(p_public text, p_private jsonb)
RETURNS text
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_public text;
BEGIN
  IF p_public !~ '^[A-Za-z0-9_-]{80,100}$' OR p_private ->> 'd' IS NULL THEN
    RAISE EXCEPTION 'Invalid VAPID key pair' USING ERRCODE = '22023';
  END IF;
  UPDATE engagement_private.config c
  SET vapid_public = p_public, vapid_private = p_private, updated_at = now()
  WHERE c.id AND c.vapid_public IS NULL;
  SELECT c.vapid_public INTO v_public FROM engagement_private.config c WHERE c.id;
  RETURN v_public;
END;
$$;
REVOKE ALL ON FUNCTION public._push_store_vapid(text, jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public._push_store_vapid(text, jsonb) TO service_role;

-- ---------------------------------------------------------------------------
-- Subscription validation and storage
-- ---------------------------------------------------------------------------

-- base64url -> bytes, or NULL when it is not valid base64url.
CREATE OR REPLACE FUNCTION public._push_b64u(p text)
RETURNS bytea
LANGUAGE plpgsql IMMUTABLE
SET search_path = ''
AS $$
DECLARE
  v text := translate(rtrim(COALESCE(p, ''), '='), '-_', '+/');
BEGIN
  IF v = '' OR v !~ '^[A-Za-z0-9+/]+$' THEN
    RETURN NULL;
  END IF;
  RETURN decode(v || repeat('=', (4 - length(v) % 4) % 4), 'base64');
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
$$;
REVOKE ALL ON FUNCTION public._push_b64u(text) FROM PUBLIC, anon, authenticated;

-- Saves a browser's subscription for one recipient (exactly one of p_user / p_employee).
-- Only the real push services are accepted, so the server never posts anywhere else.
CREATE OR REPLACE FUNCTION public._push_save(
  p_company uuid, p_user uuid, p_employee uuid, p_subscription jsonb, p_device text
)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_endpoint text := p_subscription ->> 'endpoint';
  v_p256dh text := p_subscription #>> '{keys,p256dh}';
  v_auth text := p_subscription #>> '{keys,auth}';
  v_pub bytea := public._push_b64u(v_p256dh);
  v_sec bytea := public._push_b64u(v_auth);
  v_device text := left(COALESCE(NULLIF(btrim(p_device), ''), 'Browser'), 80);
  v_before public.push_subscriptions;
  v_created boolean;
  v_devices integer;
BEGIN
  IF v_endpoint IS NULL OR char_length(v_endpoint) < 20 OR char_length(v_endpoint) > 2048 THEN
    RETURN json_build_object('error', 'The notification address is missing or too long.');
  END IF;
  IF v_endpoint !~ '^https://(fcm\.googleapis\.com|android\.googleapis\.com|([a-z0-9-]+\.)*push\.services\.mozilla\.com|([a-z0-9-]+\.)*notify\.windows\.com|([a-z0-9-]+\.)*push\.apple\.com)/' THEN
    RETURN json_build_object('error', 'This browser''s notification service is not supported. Use Chrome, Edge, Firefox or Safari.');
  END IF;
  IF v_pub IS NULL OR length(v_pub) <> 65 OR get_byte(v_pub, 0) <> 4 OR v_sec IS NULL OR length(v_sec) <> 16 THEN
    RETURN json_build_object('error', 'The browser''s notification keys are missing or invalid.');
  END IF;

  SELECT * INTO v_before FROM public.push_subscriptions s WHERE s.endpoint = v_endpoint;
  v_created := v_before.id IS NULL
    OR v_before.user_id IS DISTINCT FROM p_user
    OR v_before.employee_id IS DISTINCT FROM p_employee;

  -- The same browser used by someone else now notifies them instead.
  INSERT INTO public.push_subscriptions (company_id, user_id, employee_id, endpoint, p256dh, auth, device)
  VALUES (p_company, p_user, p_employee, v_endpoint, v_p256dh, v_auth, v_device)
  ON CONFLICT (endpoint) DO UPDATE SET
    company_id = EXCLUDED.company_id,
    user_id = EXCLUDED.user_id,
    employee_id = EXCLUDED.employee_id,
    p256dh = EXCLUDED.p256dh,
    auth = EXCLUDED.auth,
    device = EXCLUDED.device,
    created_at = CASE WHEN v_created THEN now() ELSE public.push_subscriptions.created_at END,
    failures = 0,
    last_error = NULL;

  -- At most 8 devices per person; the least recently working go first.
  DELETE FROM public.push_subscriptions s
  WHERE s.id IN (
    SELECT x.id FROM public.push_subscriptions x
    WHERE (p_user IS NOT NULL AND x.user_id = p_user) OR (p_employee IS NOT NULL AND x.employee_id = p_employee)
    ORDER BY COALESCE(x.last_ok_at, x.created_at) DESC, x.id DESC
    OFFSET 8
  );

  SELECT count(*)::int INTO v_devices FROM public.push_subscriptions x
  WHERE (p_user IS NOT NULL AND x.user_id = p_user) OR (p_employee IS NOT NULL AND x.employee_id = p_employee);

  RETURN json_build_object('ok', true, 'created', v_created, 'devices', v_devices);
END;
$$;
REVOKE ALL ON FUNCTION public._push_save(uuid, uuid, uuid, jsonb, text) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public._push_devices_json(p_user uuid, p_employee uuid)
RETURNS json
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(json_agg(json_build_object(
    'id', s.id, 'device', s.device, 'created_at', s.created_at, 'last_ok_at', s.last_ok_at,
    'last_error', s.last_error, 'failures', s.failures,
    'endpoint_hash', encode(extensions.digest(s.endpoint, 'sha256'), 'hex')
  ) ORDER BY COALESCE(s.last_ok_at, s.created_at) DESC), '[]'::json)
  FROM public.push_subscriptions s
  WHERE (p_user IS NOT NULL AND s.user_id = p_user) OR (p_employee IS NOT NULL AND s.employee_id = p_employee)
$$;
REVOKE ALL ON FUNCTION public._push_devices_json(uuid, uuid) FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Staff RPCs (any staff role: owner, HR, Finance all get notifications)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.push_subscribe(p_subscription jsonb, p_device text DEFAULT NULL, p_welcome boolean DEFAULT true)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public.auth_company_id();
  v_result json;
BEGIN
  IF auth.uid() IS NULL OR v_company IS NULL OR NOT public.auth_is_staff() THEN
    RAISE EXCEPTION 'not allowed' USING ERRCODE = '42501';
  END IF;
  v_result := public._push_save(v_company, auth.uid(), NULL, p_subscription, p_device);
  IF COALESCE((v_result ->> 'created')::boolean, false) AND COALESCE(p_welcome, true) THEN
    PERFORM public.notify_user(v_company, auth.uid(), 'push.welcome', 'Notifications are on for this device',
      'Approvals, messages and announcements will reach you here, even when AdiCorp is closed.', '/notifications');
  END IF;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.push_unsubscribe(p_endpoint text)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_count integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not allowed' USING ERRCODE = '42501';
  END IF;
  DELETE FROM public.push_subscriptions s WHERE s.user_id = auth.uid() AND s.endpoint = p_endpoint;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN json_build_object('ok', true, 'removed', v_count);
END;
$$;

CREATE OR REPLACE FUNCTION public.push_remove_device(p_id uuid)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_count integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not allowed' USING ERRCODE = '42501';
  END IF;
  DELETE FROM public.push_subscriptions s WHERE s.user_id = auth.uid() AND s.id = p_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN json_build_object('ok', true, 'removed', v_count);
END;
$$;

CREATE OR REPLACE FUNCTION public.push_devices()
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not allowed' USING ERRCODE = '42501';
  END IF;
  RETURN public._push_devices_json(auth.uid(), NULL);
END;
$$;

CREATE OR REPLACE FUNCTION public.push_test()
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_company uuid := public.auth_company_id();
  v_devices integer;
BEGIN
  IF auth.uid() IS NULL OR v_company IS NULL OR NOT public.auth_is_staff() THEN
    RAISE EXCEPTION 'not allowed' USING ERRCODE = '42501';
  END IF;
  SELECT count(*)::int INTO v_devices FROM public.push_subscriptions s WHERE s.user_id = auth.uid();
  IF v_devices = 0 THEN
    RETURN json_build_object('error', 'Turn on notifications on this device first.');
  END IF;
  IF (SELECT count(*) FROM public.notifications n
      WHERE n.user_id = auth.uid() AND n.kind = 'push.test' AND n.created_at > now() - interval '10 minutes') >= 6 THEN
    RETURN json_build_object('error', 'That is enough tests for now. Try again in a few minutes.');
  END IF;
  PERFORM public.notify_user(v_company, auth.uid(), 'push.test', 'Test notification',
    'If you can see this on your device, notifications work.', '/notifications');
  RETURN json_build_object('ok', true, 'devices', v_devices);
END;
$$;

REVOKE ALL ON FUNCTION public.push_subscribe(jsonb, text, boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.push_unsubscribe(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.push_remove_device(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.push_devices() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.push_test() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.push_subscribe(jsonb, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.push_unsubscribe(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.push_remove_device(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.push_devices() TO authenticated;
GRANT EXECUTE ON FUNCTION public.push_test() TO authenticated;

-- ---------------------------------------------------------------------------
-- Portal RPCs
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.portal_push_subscribe(p_token text, p_subscription jsonb, p_device text DEFAULT NULL, p_welcome boolean DEFAULT true)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_emp public.employees := public._portal_employee(p_token);
  v_result json;
BEGIN
  v_result := public._push_save(v_emp.company_id, NULL, v_emp.id, p_subscription, p_device);
  IF COALESCE((v_result ->> 'created')::boolean, false) AND COALESCE(p_welcome, true) THEN
    PERFORM public.notify_employee(v_emp.company_id, v_emp.id, 'push.welcome', 'Notifications are on for this device',
      'Leave decisions, messages and announcements will reach you here, even when the portal is closed.', '/portal');
  END IF;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_push_unsubscribe(p_token text, p_endpoint text)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_emp public.employees := public._portal_employee(p_token);
  v_count integer;
BEGIN
  DELETE FROM public.push_subscriptions s WHERE s.employee_id = v_emp.id AND s.endpoint = p_endpoint;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN json_build_object('ok', true, 'removed', v_count);
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_push_remove_device(p_token text, p_id uuid)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_emp public.employees := public._portal_employee(p_token);
  v_count integer;
BEGIN
  DELETE FROM public.push_subscriptions s WHERE s.employee_id = v_emp.id AND s.id = p_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN json_build_object('ok', true, 'removed', v_count);
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_push_devices(p_token text)
RETURNS json
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_emp public.employees := public._portal_employee(p_token);
BEGIN
  RETURN public._push_devices_json(NULL, v_emp.id);
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_push_test(p_token text)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_emp public.employees := public._portal_employee(p_token);
  v_devices integer;
BEGIN
  SELECT count(*)::int INTO v_devices FROM public.push_subscriptions s WHERE s.employee_id = v_emp.id;
  IF v_devices = 0 THEN
    RETURN json_build_object('error', 'Turn on notifications on this device first.');
  END IF;
  IF (SELECT count(*) FROM public.notifications n
      WHERE n.employee_id = v_emp.id AND n.kind = 'push.test' AND n.created_at > now() - interval '10 minutes') >= 6 THEN
    RETURN json_build_object('error', 'That is enough tests for now. Try again in a few minutes.');
  END IF;
  PERFORM public.notify_employee(v_emp.company_id, v_emp.id, 'push.test', 'Test notification',
    'If you can see this on your device, notifications work.', '/portal');
  RETURN json_build_object('ok', true, 'devices', v_devices);
END;
$$;

REVOKE ALL ON FUNCTION public.portal_push_subscribe(text, jsonb, text, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.portal_push_unsubscribe(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.portal_push_remove_device(text, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.portal_push_devices(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.portal_push_test(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.portal_push_subscribe(text, jsonb, text, boolean) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_push_unsubscribe(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_push_remove_device(text, uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_push_devices(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_push_test(text) TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- Delivery: every notification insert queues one async call to push-send
-- ---------------------------------------------------------------------------
-- push-send is deployed with verify_jwt=true, so the call carries the project's anon JWT
-- (the public publishable key, also in src/integrations/supabase/client.ts) in Authorization.
-- It only gets the request past the gateway; push-send still requires x-push-secret.
ALTER TABLE engagement_private.config ADD COLUMN IF NOT EXISTS function_key text;

UPDATE engagement_private.config c
SET function_key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVteWJqbXV6YnhmeGR0YnVtZ21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTY3MzUsImV4cCI6MjA2MzEzMjczNX0.ODvajzrDaKfqDOzXGNwEr4CaAYRgPY38e-vYeVTS5OY', updated_at = now()
WHERE c.id AND c.function_key IS DISTINCT FROM 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVteWJqbXV6YnhmeGR0YnVtZ21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTY3MzUsImV4cCI6MjA2MzEzMjczNX0.ODvajzrDaKfqDOzXGNwEr4CaAYRgPY38e-vYeVTS5OY';

CREATE OR REPLACE FUNCTION public.tg_notifications_push()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_url text;
  v_secret text;
  v_key text;
  v_headers jsonb;
BEGIN
  IF NEW.user_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM public.push_subscriptions s WHERE s.user_id = NEW.user_id) THEN
      RETURN NULL;
    END IF;
  ELSIF NEW.employee_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM public.push_subscriptions s WHERE s.employee_id = NEW.employee_id) THEN
      RETURN NULL;
    END IF;
  ELSE
    RETURN NULL;
  END IF;

  SELECT c.function_url, c.webhook_secret, c.function_key INTO v_url, v_secret, v_key
  FROM engagement_private.config c WHERE c.id;
  IF v_url IS NULL OR v_secret IS NULL THEN
    RETURN NULL;
  END IF;

  v_headers := jsonb_build_object('Content-Type', 'application/json', 'x-push-secret', v_secret);
  IF v_key IS NOT NULL THEN
    v_headers := v_headers || jsonb_build_object('Authorization', 'Bearer ' || v_key, 'apikey', v_key);
  END IF;

  PERFORM net.http_post(
    url := v_url,
    body := jsonb_build_object('notification_id', NEW.id),
    headers := v_headers,
    timeout_milliseconds := 10000
  );
  RETURN NULL;
EXCEPTION WHEN OTHERS THEN
  -- Push is best effort: the in-app notification is always kept.
  RETURN NULL;
END;
$$;
REVOKE ALL ON FUNCTION public.tg_notifications_push() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS notifications_push ON public.notifications;
CREATE TRIGGER notifications_push
  AFTER INSERT ON public.notifications
  FOR EACH ROW EXECUTE FUNCTION public.tg_notifications_push();

-- ---------------------------------------------------------------------------
-- 09:00 celebration greetings (pg_cron, every 15 minutes; once per person per day)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pg_cron is not available (%); morning greetings are off.', SQLERRM;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'cron') THEN
    EXECUTE $cron$SELECT cron.schedule('engagement-morning-greetings', '*/15 * * * *', 'SELECT public.engagement_send_morning_greetings()')$cron$;
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Could not schedule the morning greetings (%).', SQLERRM;
END $$;
