// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umybjmuzbxfxdtbumgma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVteWJqbXV6YnhmeGR0YnVtZ21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTY3MzUsImV4cCI6MjA2MzEzMjczNX0.ODvajzrDaKfqDOzXGNwEr4CaAYRgPY38e-vYeVTS5OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);